# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ResponseObject(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, speed: float=None, travel_time: float=None, start_time: str=None, end_time: str=None, travel_path: str=None):
        """
        ResponseObject - a model defined in Swagger

        :param speed: The speed of this ResponseObject.
        :type speed: float
        :param travel_time: The travel_time of this ResponseObject.
        :type travel_time: float
        :param start_time: The start_time of this ResponseObject.
        :type start_time: str
        :param end_time: The end_time of this ResponseObject.
        :type end_time: str
        :param travel_path: The travel_path of this ResponseObject.
        :type travel_path: str
        """
        self.swagger_types = {
            'speed': float,
            'travel_time': float,
            'start_time': str,
            'end_time': str,
            'travel_path': str
        }

        self.attribute_map = {
            'speed': 'speed',
            'travel_time': 'travel_time',
            'start_time': 'start_time',
            'end_time': 'end_time',
            'travel_path': 'travel_path'
        }

        self._speed = speed
        self._travel_time = travel_time
        self._start_time = start_time
        self._end_time = end_time
        self._travel_path = travel_path

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseObject':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseObject of this ResponseObject.
        :rtype: ResponseObject
        """
        return deserialize_model(dikt, cls)

    @property
    def speed(self) -> float:
        """
        Gets the speed of this ResponseObject.
        The average speed in kmph.

        :return: The speed of this ResponseObject.
        :rtype: float
        """
        return self._speed

    @speed.setter
    def speed(self, speed: float):
        """
        Sets the speed of this ResponseObject.
        The average speed in kmph.

        :param speed: The speed of this ResponseObject.
        :type speed: float
        """

        self._speed = speed

    @property
    def travel_time(self) -> float:
        """
        Gets the travel_time of this ResponseObject.
        Time it took to travel length in seconds.

        :return: The travel_time of this ResponseObject.
        :rtype: float
        """
        return self._travel_time

    @travel_time.setter
    def travel_time(self, travel_time: float):
        """
        Sets the travel_time of this ResponseObject.
        Time it took to travel length in seconds.

        :param travel_time: The travel_time of this ResponseObject.
        :type travel_time: float
        """

        self._travel_time = travel_time

    @property
    def start_time(self) -> str:
        """
        Gets the start_time of this ResponseObject.
        Start time of the data.

        :return: The start_time of this ResponseObject.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """
        Sets the start_time of this ResponseObject.
        Start time of the data.

        :param start_time: The start_time of this ResponseObject.
        :type start_time: str
        """

        self._start_time = start_time

    @property
    def end_time(self) -> str:
        """
        Gets the end_time of this ResponseObject.
        End time of the data.

        :return: The end_time of this ResponseObject.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: str):
        """
        Sets the end_time of this ResponseObject.
        End time of the data.

        :param end_time: The end_time of this ResponseObject.
        :type end_time: str
        """

        self._end_time = end_time

    @property
    def travel_path(self) -> str:
        """
        Gets the travel_path of this ResponseObject.
        Path of travel denoted by a list of travel points separated by underscore.

        :return: The travel_path of this ResponseObject.
        :rtype: str
        """
        return self._travel_path

    @travel_path.setter
    def travel_path(self, travel_path: str):
        """
        Sets the travel_path of this ResponseObject.
        Path of travel denoted by a list of travel points separated by underscore.

        :param travel_path: The travel_path of this ResponseObject.
        :type travel_path: str
        """

        self._travel_path = travel_path

